### PR TITLE
added the other DP problems

### PR DESCRIPTION
**Pull request by click2cloud-anupam**
add it plz

### CODE REVIEW

**Comment by click2cloud-anupam** [comment]
noice

**Comment by click2cloud-anupam** [comment]
## Proposed changes
- addition of memoization approach
- addition of tabulation approach
- addition of space optimized approach

**Comment by click2cloud-anupam** [comment]
### Proposed changes
- Addition of other daily problems done on LC
🏆

**Comment by click2cloud-anupam** [comment]
### Proposed changes
- added the step wise progress of coding out the triangle problem on Leetcode.
- finally added the correct solution
  - space optimized
  - tabulation approach

**Review by Anupam0401 — APPROVED** [review]

**Pull request merged**
